import { ContentItem, MediaAsset, Genre, Person } from '../types/index.ts';

export const INITIAL_GENRES: Genre[] = [
  { id: 1, name: 'Drama', slug: 'drama', description: 'Deep human emotions, struggles, and character-driven stories' },
  { id: 2, name: 'Thriller', slug: 'thriller', description: 'Suspenseful, high-stakes psychological and crime thrillers' },
  { id: 3, name: 'Mystery & Detective', slug: 'mystery', description: 'Classic investigations, whodunits, and detective puzzles' },
  { id: 4, name: 'Action & Adventure', slug: 'action', description: 'High-energy sequences, chases, and heroic journeys' },
  { id: 5, name: 'Romance', slug: 'romance', description: 'Romantic affairs, timeless love stories, and emotional bonds' },
  { id: 6, name: 'Comedy', slug: 'comedy', description: 'Satirical, situational, and lighthearted comedy' },
  { id: 7, name: 'Period & Historical', slug: 'period', description: 'Rich historical narratives, vintage Bengal, and biographical dramas' },
  { id: 8, name: 'Crime', slug: 'crime', description: 'Gritty underworld, law enforcement, and crime mysteries' },
];

export const INITIAL_PEOPLE: Person[] = [
  { id: 1, name: 'Ayan Sit', role: 'Director & Executive Producer' },
  { id: 2, name: 'Parambrata Chatterjee', role: 'Actor / Director' },
  { id: 3, name: 'Anirban Bhattacharya', role: 'Actor / Director' },
  { id: 4, name: 'Raima Sen', role: 'Lead Actor' },
  { id: 5, name: 'Saswata Chatterjee', role: 'Lead Actor' },
  { id: 6, name: 'Swastika Mukherjee', role: 'Lead Actor' },
];

export const INITIAL_CONTENT: ContentItem[] = [
  {
    id: 101,
    type: 'MOVIE',
    title: 'The Kolkata Files: Shadows of Park Street',
    slug: 'the-kolkata-files-shadows-of-park-street',
    shortDescription: 'An elite detective uncovers a high-profile conspiracy hidden under the neon lights of Kolkata.',
    fullDescription: 'Set against the rain-drenched streets of central Kolkata, veteran investigator Subrata Sen is called in to examine an unexplained disappearance during a winter carnival. What begins as a missing person inquiry rapidly turns into a high-stakes cat-and-mouse game through vintage alleyways and corporate corridors.',
    releaseDate: '2025-11-15',
    releaseYear: 2025,
    duration: 134,
    language: 'Bengali',
    country: 'India',
    ageRating: '16+',
    accessType: 'PREMIUM',
    isPublished: true,
    publishedAt: '2025-11-15T00:00:00Z',
    masterVideoStatus: 'UPLOADED',
    posterUrl: 'https://images.unsplash.com/photo-1536440136628-849c177e76a1?w=800&auto=format&fit=crop&q=80',
    landscapeUrl: 'https://images.unsplash.com/photo-1489599849997-425fc5c5553b?w=1200&auto=format&fit=crop&q=80',
    heroUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=1600&auto=format&fit=crop&q=80',
    trailerUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
    isArchived: false,
    createdAt: '2025-11-10T08:00:00Z',
    updatedAt: '2025-11-15T10:00:00Z',
    genres: [
      { id: 2, name: 'Thriller', slug: 'thriller' },
      { id: 3, name: 'Mystery & Detective', slug: 'mystery' },
    ],
    castCrew: [
      { personId: 1, name: 'Ayan Sit', role: 'Director' },
      { personId: 2, name: 'Parambrata Chatterjee', role: 'Lead Actor', characterName: 'Inspector Subrata Sen' },
      { personId: 4, name: 'Raima Sen', role: 'Lead Actor', characterName: 'Dr. Nandini Roy' },
    ],
  },
  {
    id: 102,
    type: 'WEB_SERIES',
    title: 'Mahanagar Nights (Season 1)',
    slug: 'mahanagar-nights-season-1',
    shortDescription: 'Six lives intersect across one fateful midnight in modern metropolis Kolkata.',
    fullDescription: 'A gripping multi-threaded neo-noir web series highlighting the contrast between the affluent high-rises of Salt Lake and the gritty dockyards of Khidirpur. A tech executive, a taxi driver, a crime journalist, and a theater artist find their destinies locked together.',
    releaseDate: '2026-01-20',
    releaseYear: 2026,
    duration: 240,
    language: 'Bengali',
    country: 'India',
    ageRating: '18+',
    accessType: 'PREMIUM',
    isPublished: true,
    publishedAt: '2026-01-20T00:00:00Z',
    masterVideoStatus: 'UPLOADED',
    posterUrl: 'https://images.unsplash.com/photo-1509281373149-e957c6296406?w=800&auto=format&fit=crop&q=80',
    landscapeUrl: 'https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?w=1200&auto=format&fit=crop&q=80',
    heroUrl: 'https://images.unsplash.com/photo-1574267432553-4b4628081c31?w=1600&auto=format&fit=crop&q=80',
    trailerUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    isArchived: false,
    createdAt: '2026-01-15T12:00:00Z',
    updatedAt: '2026-01-20T14:30:00Z',
    genres: [
      { id: 1, name: 'Drama', slug: 'drama' },
      { id: 8, name: 'Crime', slug: 'crime' },
    ],
    castCrew: [
      { personId: 3, name: 'Anirban Bhattacharya', role: 'Lead Actor', characterName: 'Rohan Banerjee' },
      { personId: 6, name: 'Swastika Mukherjee', role: 'Lead Actor', characterName: 'Mallika Sen' },
    ],
  },
  {
    id: 103,
    type: 'MOVIE',
    title: 'Eken Babu: Mystery in Darjeeling',
    slug: 'eken-babu-mystery-in-darjeeling',
    shortDescription: 'The quirky and lovable detective tackles an eccentric heritage mansion case in foggy tea gardens.',
    fullDescription: 'While vacationing in Darjeeling with his loyal companions Bapi and Pramatha, the quirky detective Ekenbabu gets entangled in a mysterious artifact theft and a wealthy tea planter will dispute.',
    releaseDate: '2025-08-10',
    releaseYear: 2025,
    duration: 118,
    language: 'Bengali',
    country: 'India',
    ageRating: '13+',
    accessType: 'FREE',
    isPublished: true,
    publishedAt: '2025-08-10T00:00:00Z',
    masterVideoStatus: 'UPLOADED',
    posterUrl: 'https://images.unsplash.com/photo-1478720568477-152d9b164e26?w=800&auto=format&fit=crop&q=80',
    landscapeUrl: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=1200&auto=format&fit=crop&q=80',
    heroUrl: 'https://images.unsplash.com/photo-1485846234645-a62644f84728?w=1600&auto=format&fit=crop&q=80',
    trailerUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    isArchived: false,
    createdAt: '2025-08-01T09:00:00Z',
    updatedAt: '2025-08-10T11:00:00Z',
    genres: [
      { id: 3, name: 'Mystery & Detective', slug: 'mystery' },
      { id: 6, name: 'Comedy', slug: 'comedy' },
    ],
    castCrew: [
      { personId: 1, name: 'Ayan Sit', role: 'Producer' },
      { personId: 3, name: 'Anirban Bhattacharya', role: 'Lead Actor', characterName: 'Ekendra Sen' },
    ],
  },
  {
    id: 104,
    type: 'DOCUMENTARY',
    title: 'Ganga: The Eternal River of Bengal',
    slug: 'ganga-the-eternal-river-of-bengal',
    shortDescription: 'A visual celebration of the artisans, ghats, and spiritual folklore of the Ganges delta.',
    fullDescription: 'Filmed over two years across Murshidabad, Nabadwip, Kolkata, and the Sundarbans, this 4K documentary chronicles the cultural heritage, boatmakers, and riverine communities that define Bengal.',
    releaseDate: '2025-04-14',
    releaseYear: 2025,
    duration: 88,
    language: 'Bengali',
    country: 'India',
    ageRating: 'ALL',
    accessType: 'FREE',
    isPublished: true,
    publishedAt: '2025-04-14T00:00:00Z',
    masterVideoStatus: 'UPLOADED',
    posterUrl: 'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=800&auto=format&fit=crop&q=80',
    landscapeUrl: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=1200&auto=format&fit=crop&q=80',
    heroUrl: 'https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=1600&auto=format&fit=crop&q=80',
    trailerUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    isArchived: false,
    createdAt: '2025-04-01T10:00:00Z',
    updatedAt: '2025-04-14T12:00:00Z',
    genres: [
      { id: 7, name: 'Period & Historical', slug: 'period' },
      { id: 1, name: 'Drama', slug: 'drama' },
    ],
    castCrew: [
      { personId: 1, name: 'Ayan Sit', role: 'Director' },
    ],
  },
];

export const INITIAL_MEDIA_ASSETS: MediaAsset[] = [
  {
    id: 501,
    contentId: 101,
    assetType: 'MASTER_VIDEO',
    storageProvider: 'Cloudflare R2 (Bucket: ayan)',
    storageKey: 'janala/movies/101/master/the-kolkata-files-master.mp4',
    originalFileName: 'the-kolkata-files-master-prores.mp4',
    mimeType: 'video/mp4',
    fileSize: '4823450912',
    status: 'UPLOADED',
    etag: '"72161e7dfa2d62e802747c593b202772"',
    downloadUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
    isCurrent: true,
    createdAt: '2025-11-14T10:30:00Z',
  },
  {
    id: 502,
    contentId: 102,
    assetType: 'MASTER_VIDEO',
    storageProvider: 'Cloudflare R2 (Bucket: ayan)',
    storageKey: 'janala/series/102/s01/e01/mahanagar-nights-ep1.mp4',
    originalFileName: 'mahanagar-nights-ep1-master.mp4',
    mimeType: 'video/mp4',
    fileSize: '3128945120',
    status: 'UPLOADED',
    etag: '"61fb1c91a19b595b9e0e767447383afe"',
    downloadUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    isCurrent: true,
    createdAt: '2026-01-18T14:20:00Z',
  },
  {
    id: 503,
    contentId: 103,
    assetType: 'MASTER_VIDEO',
    storageProvider: 'Cloudflare R2 (Bucket: ayan)',
    storageKey: 'janala/movies/103/master/eken-babu-darjeeling.mp4',
    originalFileName: 'eken-babu-master-1080p.mp4',
    mimeType: 'video/mp4',
    fileSize: '2987140800',
    status: 'UPLOADED',
    etag: '"7c2d65330e9a65c59d624ec20d8c9926"',
    downloadUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    isCurrent: true,
    createdAt: '2025-08-09T09:15:00Z',
  },
  {
    id: 504,
    contentId: 104,
    assetType: 'MASTER_VIDEO',
    storageProvider: 'Cloudflare R2 (Bucket: ayan)',
    storageKey: 'janala/documentaries/104/master/ganga-eternal-river.mp4',
    originalFileName: 'ganga-eternal-4k-master.mp4',
    mimeType: 'video/mp4',
    fileSize: '5412890123',
    status: 'UPLOADED',
    etag: '"bd9a0d047c07aa3613f7e59b02def4ce"',
    downloadUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    isCurrent: true,
    createdAt: '2025-04-12T16:45:00Z',
  },
];
